apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Release.Name }}-vault-backend 
  namespace: {{ .Values.global.namespace.eso }}
spec:
  provider:
    vault:
      server: {{ .Values.vaultBackend.server | quote }}
      path: {{ .Values.vaultBackend.path | quote }}
      version: {{ .Values.vaultBackend.version | quote }}
      auth:
        tokenSecretRef:
          name: {{ .Values.vaultBackend.tokenSecretRef.name | quote }}
          key: {{ .Values.vaultBackend.tokenSecretRef.key | quote }}
          namespace: {{ .Values.global.namespace.eso }}
