apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-go-crud-app-secrets
  namespace: {{ .Values.global.namespace.app }}
spec:
  secretStoreRef:
    name: {{ .Release.Name }}-vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-go-crud-app-secrets
  data:
  - secretKey: DB_USER
    remoteRef:
      key: {{ .Values.externalSecret.data.DB_USER.key }}
      property: {{ .Values.externalSecret.data.DB_USER.property }}
  - secretKey: DB_PASSWORD
    remoteRef:
      key: {{ .Values.externalSecret.data.DB_PASSWORD.key }}
      property: {{ .Values.externalSecret.data.DB_PASSWORD.property }}
