apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-crud-app.fullname" . }}  # Dynamically set service name
  namespace: {{ .Values.global.namespace.app }}
spec:
  selector:
    app: {{ include "go-crud-app.name" . }}  # Ensure it matches Deployment labels
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
